name = "Blueprint"
author = "ItsPercent"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f5a6210b14965653a0f9e90a5ab3294d6b9f5022b752bc3587e2ac1f5cf497f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["Fabric", "Neoforge"]
